Add compression method
silvia-odwyer/photon pull request #139
Opened 2022-10-01 13:32 UTC by StckOverflw

Add a simple compress method to the library based on the solution given in issue #137

If there is a better solution to this lmk, I'd be happy to implement that instead.

Closes #137

2022-10-01 23:13 UTC, silvia-odwyer commented
@StckOverflw Hi Emma, thanks very much for the pull request, it's much appreciated! 😄 I'm just wondering if you could make the changes requested, I've marked where the fixes need to be made in the review above. After that, the test suite should pass ✅  

Thanks again, looking forward to merging the changes 👍

2022-10-02 00:15 UTC, StckOverflw commented
I'm not seeing a review. Did you forget to submit it?

2022-10-02 00:17 UTC, silvia-odwyer requested changes

2022-10-02 00:18 UTC, silvia-odwyer commented
@StckOverflw Hi Emma, It was marked pending, my apologies. The two changes I requested should be published now ✅

2022-10-02 00:32 UTC, silvia-odwyer requested changes

2022-10-02 00:32 UTC, silvia-odwyer commented on crate/src/transform.rs
> +/// use photon_rs::transform::compress
This line needs a semi-colon at the end btw, the test suite should pass then

2022-10-02 00:35 UTC, StckOverflw commented
I'm sorry, I didn't concentrate on what I was doing haha

2022-10-02 00:47 UTC, silvia-odwyer commented
@StckOverflw No problem at all haha, and thanks again for your contribution! Everything looks good, so I'm going to merge this now ✅ 👍

2022-10-02 00:47 UTC, merged

2022-10-02 01:26 UTC, silvia-odwyer reviewed
Not sure if this PR was for Hactoberfest, but it should count as I've added the `hacktoberfest-accepted` label to this PR. I can't seem to approve the PR, not sure if that's needed for a PR to count towards Hacktoberfest. Anyway, just wanted to let you know about that just in case

2022-10-02 01:45 UTC, silvia-odwyer commented
@StckOverflw Yeah I double-checked it, there's no way for me to approve the PR after merging ... so hopefully it should still count, but I can't be certain that being said

2022-10-02 12:11 UTC, StckOverflw commented
Yes, it counted since the repo has the hacktoberfest label, thank you!